# Generated by Django 6.0.5 on 2026-07-04 11:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.jpg",
                upload_to=accounts.models.get_avatar_path,
                verbose_name="Аватар",
            ),
        ),
    ]
